services:
  # 1. The Backend (FastAPI Python Environment)
  - type: web
    name: portafolio-markowitz-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12 # Match the version that handles pandas optimally
      - key: PORT
        value: 8000

  # 2. The Frontend (Vite Static Site)
  - type: web
    name: portafolio-markowitz-ui
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/dist"
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
